#!/usr/bin/env python2

import roslib
import rospy
import sys
import cv2
from sensor_msgs.msg import Image, CameraInfo
from cv_bridge import CvBridge, CvBridgeError
from mavros_msgs.srv import *
import numpy as np

class cvBridgeDemo():
    def __init__(self):
        self.node_name = "cv_bridge_demo"
        
        rospy.init_node(self.node_name)
        
        # What we do during shutdown
        rospy.on_shutdown(self.cleanup)
                
        # Create the cv_bridge object
        self.bridge = CvBridge()

        self.x_percent = 0.30
        self.y_percent = 0.30
        self.mode = "LOITER"
        
        # Subscribe to the camera image and depth topics and set
        # the appropriate callbacks
        self.depth_sub = rospy.Subscriber("/d400/depth/image_rect_raw", Image, self.depth_callback)
        
        rospy.loginfo("Waiting for image topics...")

               
    def depth_callback(self, ros_image):
        # The depth image is a single-channel float32 image
        depth_image = self.bridge.imgmsg_to_cv2(ros_image)
        np_image = np.array(depth_image)
        

        
        min_x = int(np_image.shape[0]*self.x_percent)
        max_x = int(np_image.shape[0]*(1-self.x_percent))
        min_y = int(np_image.shape[1]*self.y_percent)
        max_y = int(np_image.shape[1]*(1-self.y_percent))
        
        #print(min_x, max_x, min_y, max_y)
        
        np_region = np_image[min_x:max_x, min_y:max_y]
        #print(np_region.shape)
        distance = np.min(np_region[np_region > 0])/1000.0
        print("distance: " + str(distance) + " m, mode: " + self.mode)

        rospy.wait_for_service('/mavros/set_mode')
        if distance < 1 and self.mode == "LOITER":
            try:
                flightModeService = rospy.ServiceProxy('/mavros/set_mode', mavros_msgs.srv.SetMode)
                isModeChanged = flightModeService(custom_mode='BRAKE') #return true or false
                print("set brake")
                print(isModeChanged)
                self.mode = "BRAKE"
            except rospy.ServiceException, e:
                print "service set_mode call failed: %s. GUIDED Mode could not be set. Check that GPS is enabled"%e
        elif distance >= 1 and self.mode == "BRAKE":
            try:
                flightModeService = rospy.ServiceProxy('/mavros/set_mode', mavros_msgs.srv.SetMode)
                isModeChanged = flightModeService(custom_mode='LOITER') #return true or false
                print("set loiter")
                print(isModeChanged)
                self.mode = "LOITER"
            except rospy.ServiceException, e:
                print "service set_mode call failed: %s. GUIDED Mode could not be set. Check that GPS is enabled"%e
        
        
        # Display the result
        #cv2.imshow("Depth Image", depth_image)
        #cv2.waitKey(1)
    
    def cleanup(self):
        print "Shutting down vision node."
        cv2.destroyAllWindows()   
    
def main(args):       
    try:
        cvBridgeDemo()
        rospy.spin()
    except KeyboardInterrupt:
        print "Shutting down vision node."
        cv2.DestroyAllWindows()

if __name__ == '__main__':
    main(sys.argv)
    